### ISSUE TITLE
Support for alt text on links

### ISSUE THREAD

**Issue by tjvf** [laurencedawson/reddit-sync-development#830]
Some subreddits, including Japanese learning subs, use alt-text so much that the subs are practically unusable without it. In the case of Japanese learning subs, they use it to show the readings of complex Kanji (Chinese characters) with a much easier phonetic alphabet.

It would be great if there was some way to long press a link and select "View Alt Text" or something like that.

**Comment by laurencedawson** [comment]
Do you have an example link? Cheers.

**Comment by TJFadness** [comment]
Sure! Here are a few:
https://www.reddit.com/r/LearnJapanese/comments/31zi42/difference_between_a%E3%81%AFb%E3%82%88%E3%82%8Aadjective%E3%81%A7%E3%81%99_and/cq6g3x7
https://www.reddit.com/r/LearnJapanese/comments/321d24/what_are_your_favorite_tonguetwisters/cq6xfdb
https://www.reddit.com/r/LearnJapanese/comments/275cea/simple_jlpt_n5_kanji_chart/chxw8ov

In that sub, they display the alt text above the link, allowing you to include readings of characters.

Alt text is added in reddit like this: [link text](http://www.example.com "Alt text")

**Comment by bdr99** [comment]
For reference, this is the CSS that /r/LearnJapanese uses in order to display the character readings above the text. I browse this subreddit frequently, and it would be fantastic if Sync for Reddit could render these character readings, or at least provide a way to view them manually.

```css
a[href$="/fg"],
a[href$="#fg"] {
    cursor: default!important;
    text-decoration: none;
    line-height: 1;
    text-align: center;
    display: inline-block;
    color: inherit!important
}
a[href$="/fg"]:before,
a[href$="#fg"]:before {
    font-size: 0.70em;
    font-weight: normal;
    line-height: 1.2;
    cursor: pointer;
    text-decoration: none;
    display: block;
    content: attr(title)
}
```
